from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

DOMAIN = "circutor_eds"
DEFAULT_SCAN_INTERVAL = 30
CONF_HOST = "host"
CONF_DEVICE_ID = "device_id"

# (friendly_name, unit, device_class, state_class, icon)
SENSOR_TYPES: dict[str, tuple] = {
    "AE":          ("Energia activa",              "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "COSI":        ("Factor de potencia",           None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "API":         ("Potencia activa",              "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "CPI":         ("Potencia capacitiva",          "kvarC",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPI":         ("Potencia inductiva",           "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "NCOST":       ("Coste normalizado",            "€",      SensorDeviceClass.MONETARY,      SensorStateClass.TOTAL_INCREASING, "mdi:currency-eur"),
    "KGCO2":       ("Emisiones CO2",                "kg",     SensorDeviceClass.WEIGHT,        SensorStateClass.TOTAL_INCREASING, "mdi:molecule-co2"),
    "HZI":         ("Frecuencia",                   "Hz",     SensorDeviceClass.FREQUENCY,     SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "AI1":         ("Corriente L1",                 "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "AI2":         ("Corriente L2",                 "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "AI3":         ("Corriente L3",                 "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "VI1":         ("Tension fase-neutro L1",       "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VI2":         ("Tension fase-neutro L2",       "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VI3":         ("Tension fase-neutro L3",       "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "ANI":         ("Corriente de neutro",          "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "RPCI":        ("Potencia reactiva",            "kvarC",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "KDVI":        ("Distorsion de tension",        "%",      None,                            SensorStateClass.MEASUREMENT,      "mdi:percent"),
    "KAVI":        ("Asimetria de tension",         "%",      None,                            SensorStateClass.MEASUREMENT,      "mdi:percent"),
    "KDAI":        ("Distorsion de corriente",      "%",      None,                            SensorStateClass.MEASUREMENT,      "mdi:percent"),
    "KAAI":        ("Asimetria de corriente",       "%",      None,                            SensorStateClass.MEASUREMENT,      "mdi:percent"),
    "ICEVQ1":      ("Indice calidad electrica",     None,     None,                            SensorStateClass.MEASUREMENT,      "mdi:check-circle"),
    "VI123":       ("Tension fase-neutro III",      "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VNI":         ("Tension de neutro",            "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "AI":          ("Corriente de fase",            "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "RE":          ("Energia reactiva",             "kvarCh", None,                            SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "FWAI1":       ("Corriente armonica 1",         "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "FWAI2":       ("Corriente armonica 2",         "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "AE1":         ("Energia activa L1",            "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "AE2":         ("Energia activa L2",            "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "AE3":         ("Energia activa L3",            "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "AEB":         ("Energia activa periodo",       "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.MEASUREMENT,      "mdi:lightning-bolt"),
    "AEE":         ("Energia activa acumulada",     "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "AET1":        ("Energia activa tarifa 1",      "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "AET2":        ("Energia activa tarifa 2",      "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "IE":          ("Energia importada",            "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "IE1":         ("Energia importada L1",         "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "IE2":         ("Energia importada L2",         "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "IE3":         ("Energia importada L3",         "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "IEB":         ("Energia importada periodo",    "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.MEASUREMENT,      "mdi:lightning-bolt"),
    "IEE":         ("Energia importada acumulada",  "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "VAE":         ("Energia aparente",             "kVAh",   None,                            SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "VAI":         ("Potencia aparente",            "kVA",    None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VAI1":        ("Potencia aparente L1",         "kVA",    None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VAI2":        ("Potencia aparente L2",         "kVA",    None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VAI3":        ("Potencia aparente L3",         "kVA",    None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "CE":          ("Energia exportada",            "kWh",    SensorDeviceClass.ENERGY,        SensorStateClass.TOTAL_INCREASING, "mdi:lightning-bolt"),
    "DAI1":        ("Demanda corriente L1",         "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "DAI2":        ("Demanda corriente L2",         "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "DAI3":        ("Demanda corriente L3",         "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "DVI1":        ("Desviacion tension L1",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "DVI2":        ("Desviacion tension L2",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "DVI3":        ("Desviacion tension L3",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "PFI":         ("Factor de potencia total",     None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "PFI1":        ("Factor de potencia L1",        None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "PFI2":        ("Factor de potencia L2",        None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "PFI3":        ("Factor de potencia L3",        None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "COSI1":       ("Cos fi L1",                    None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "COSI2":       ("Cos fi L2",                    None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "COSI3":       ("Cos fi L3",                    None,     SensorDeviceClass.POWER_FACTOR,  SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "API1":        ("Potencia activa L1",           "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "API2":        ("Potencia activa L2",           "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "API3":        ("Potencia activa L3",           "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "CPI1":        ("Potencia capacitiva L1",       "kvarC",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "CPI2":        ("Potencia capacitiva L2",       "kvarC",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "CPI3":        ("Potencia capacitiva L3",       "kvarC",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPI1":        ("Potencia inductiva L1",        "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPI2":        ("Potencia inductiva L2",        "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPI3":        ("Potencia inductiva L3",        "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "AMX1":        ("Corriente max L1",             "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "AMX2":        ("Corriente max L2",             "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "AMX3":        ("Corriente max L3",             "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "APMX":        ("Potencia activa maxima",       "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "APMX1":       ("Potencia activa max L1",       "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "APMX2":       ("Potencia activa max L2",       "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "APMX3":       ("Potencia activa max L3",       "kW",     SensorDeviceClass.POWER,         SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPMX":        ("Potencia inductiva maxima",    "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPMX1":       ("Potencia inductiva max L1",    "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPMX2":       ("Potencia inductiva max L2",    "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "IPMX3":       ("Potencia inductiva max L3",    "kvarL",  None,                            SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VMX1":        ("Tension max L1",               "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VMX2":        ("Tension max L2",               "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VMX3":        ("Tension max L3",               "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VI12":        ("Tension fase-fase L12",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VI23":        ("Tension fase-fase L23",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "VI31":        ("Tension fase-fase L31",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "HZMN":        ("Frecuencia minima",            "Hz",     SensorDeviceClass.FREQUENCY,     SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "HZMX":        ("Frecuencia maxima",            "Hz",     SensorDeviceClass.FREQUENCY,     SensorStateClass.MEASUREMENT,      "mdi:sine-wave"),
    "COST":        ("Coste energia",                "€",      SensorDeviceClass.MONETARY,      SensorStateClass.TOTAL_INCREASING, "mdi:currency-eur"),
    "COSTT1":      ("Coste tarifa 1",               "€",      SensorDeviceClass.MONETARY,      SensorStateClass.TOTAL_INCREASING, "mdi:currency-eur"),
    "COSTT2":      ("Coste tarifa 2",               "€",      SensorDeviceClass.MONETARY,      SensorStateClass.TOTAL_INCREASING, "mdi:currency-eur"),
    "KGCO2T1":     ("Emisiones CO2 tarifa 1",       "kg",     SensorDeviceClass.WEIGHT,        SensorStateClass.TOTAL_INCREASING, "mdi:molecule-co2"),
    "KGCO2T2":     ("Emisiones CO2 tarifa 2",       "kg",     SensorDeviceClass.WEIGHT,        SensorStateClass.TOTAL_INCREASING, "mdi:molecule-co2"),
    "NCOSTT1":     ("Coste norm. tarifa 1",         "€",      SensorDeviceClass.MONETARY,      SensorStateClass.TOTAL_INCREASING, "mdi:currency-eur"),
    "NCOSTT2":     ("Coste norm. tarifa 2",         "€",      SensorDeviceClass.MONETARY,      SensorStateClass.TOTAL_INCREASING, "mdi:currency-eur"),
    "STATUS":      ("Estado",                       None,     None,                            None,                              "mdi:check-circle"),
    "TIME":        ("Tiempo",                       "s",      SensorDeviceClass.DURATION,      SensorStateClass.TOTAL_INCREASING, "mdi:clock"),
    "ALARMSTATE1": ("Alarma 1",                     None,     None,                            None,                              "mdi:alarm-light"),
    "ALARMSTATE2": ("Alarma 2",                     None,     None,                            None,                              "mdi:alarm-light"),
    "ALARMSTATE3": ("Alarma 3",                     None,     None,                            None,                              "mdi:alarm-light"),
    "ALARMSTATE4": ("Alarma 4",                     None,     None,                            None,                              "mdi:alarm-light"),
    "ARM1A1":      ("Armonico 1 corriente L1",      "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "ARM1A2":      ("Armonico 1 corriente L2",      "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "ARM1V1":      ("Armonico 1 tension L1",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "ARM1V2":      ("Armonico 1 tension L2",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "ARM2A1":      ("Armonico 2 corriente L1",      "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "ARM2A2":      ("Armonico 2 corriente L2",      "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "ARM2V1":      ("Armonico 2 tension L1",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "ARM2V2":      ("Armonico 2 tension L2",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "ARM3A1":      ("Armonico 3 corriente L1",      "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "ARM3A2":      ("Armonico 3 corriente L2",      "A",      SensorDeviceClass.CURRENT,       SensorStateClass.MEASUREMENT,      "mdi:current-ac"),
    "ARM3V1":      ("Armonico 3 tension L1",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
    "ARM3V2":      ("Armonico 3 tension L2",        "V",      SensorDeviceClass.VOLTAGE,       SensorStateClass.MEASUREMENT,      "mdi:flash"),
}
